import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '400', '600', '700'],  // Include the weights you need
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;600;700&display=swap"
            rel="stylesheet"
          />
      </Head>
      <body className={poppins.className}>
      {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        {children}
      </body>
    </html>
  );
}
